// src/App.tsx
import React from "react";
import NavBar from "./components/Partials/NavBar";
import Home from "./routes/home/Home";

// trying to implement React router 
import { createBrowserRouter, RouterProvider } from "react-router-dom"


const router = createBrowserRouter([
  {
    path: "/",
    element: <Home/>
  },
  {
    path: "/home",
    element: <Home/>
  },

])

export default () => {
  return (
<>
    <NavBar
        Pages={["Home","Videos","Posts"]}
        Name={"Username"}
    />
    <RouterProvider router={router} />

</>
  )
}

// src/App.svelte
<script lang=ts>
  import Home from './pages/Home/Home.svelte';
  import Posts from './pages/Posts/Posts.svelte';
  import Videos from './pages/Videos/Videos.svelte';
  import Navbar from "./components/Navbar.svelte";
  import { Router, Route } from "./router/index";
</script>

<Navbar />

<main class="p-5">
  <Router>
    <Route path="/" component={Home} />
    <Route path="/posts/:id" component={Posts} />
    <Route path="/videos/:id" component={Videos} />
  </Router>
</main>
